# Generated by Django 5.0.7 on 2024-08-12 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=20)),
                ('Supervisor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Rank', models.CharField(max_length=20)),
                ('Salary', models.IntegerField()),
                ('HireDate', models.DateField()),
                ('DeptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.department')),
            ],
        ),
    ]
